### ISSUE TITLE
Empty resources/lang/i18n/[locale]/LC_MESSAGES/[domain].po files

### ISSUE THREAD

**Issue by akaroot** [xinax/laravel-gettext#10]
Hi,
After executing command
````
php artisan gettext:create
````  
.po files does not content translation strings

````bash
php artisan gettext:update                                                                                                                                            
PO file for locale: ru_RU/messages were updated successfuly
PO file for locale: uk_UA/messages were updated successfuly
Done!
2 locales were updated.


````

**Comment by shaggyz** [comment]
Hi, check documentation. Empty files are generated with that command. After this you need to use poEdit to collect translation strings (update button).

**Comment by mkwsra** [comment]
But these files are empty, even after opening it with poEdit! with text editor : Nothing except header information, therefore there is nothing to translated using poEdit.

thanks a lot in advance for sharing your knowledge with us

**Comment by shaggyz** [comment]
Please read the documentation. Files with just the header are fine, your working flow must be like this:

1- Install / configure the package
2- artisan gettext:create 
3- Open translation files with poedit and press the UPDATE button. Strings will be collected from poEdit. 
4- translate and save.

There is a picture in README with this indications.

**Comment by mkwsra** [comment]
Yes its working, Thanks!
