### ISSUE TITLE
how to use the __() in Form::label() ?

### ISSUE THREAD

**Issue by 8lbiasian** [xinax/laravel-gettext#100]
hello i want to know how to use the __() with the form:: 

for example 

{!! Form::label('name', 'Document Name', ['class' => 'control-label']) !!}

i want to add the translating to the __('Document Name')  how i can do that ?

or its not supported

**Comment by shaggyz** [comment]
This should work: ```{!! Form::label('name', __('Document Name'), ['class' => 'control-label']) !!}```

Remember run ```artisan gettext:update``` before edit PO files.
