### ISSUE TITLE
Class App not found error when running composer update

### ISSUE THREAD

**Issue by Truemedia** [xinax/laravel-gettext#101]
I get this error in the commandline when I trying installing the package for the first time:

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App' not found in /Users/wadepenistone/Code/fivethree.site/vendor/xinax/laravel-gettext/src/Xinax/LaravelGettext/Support/helpers.php on line 14

Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App' not found in /Users/wadepenistone/Code/fivethree.site/vendor/xinax/laravel-gettext/src/Xinax/LaravelGettext/Support/helpers.php on line 14

Unable to install without tweaking the package myself. Could this be fixed to avoid install grief?

**Comment by shaggyz** [comment]
Are you using Lumen or Laravel? Which version of package and framework?

**Comment by Truemedia** [comment]
Laravel 5.3 using the latest 4.x branch of this package
