### ISSUE TITLE
How to use Symfony Translator instead of gettext?

### ISSUE THREAD

**Issue by simplenotezy** [xinax/laravel-gettext#102]
After upgrading to v4 - how do we switch from gettext to Symfony Translator?

I'd like to migrate away from gettext. Currently we have everything in PO and MO files, but we have a lot of issues because of gettext (cache, etc).

**Comment by shaggyz** [comment]
After upgrade you can set/add this option to config file in order to change to Symfony handler:

```php
    /**
     * Translation handlers, options are:
     *
     * - symfony: (recommended) uses the symfony translations component. Incompatible with php-gettext
     * you must uninstall the php-gettext module before use this handler.
     *
     * - gettext: requires the php-gettext module installed. This handler has well-known cache issues
     */
    'handler' => 'symfony',
```
That's all.

**Comment by simplenotezy** [comment]
@shaggyz is translations managed the same way in .PO and .MO files? Using e.g. PoEdit to translate strings?
