### ISSUE TITLE
Undefined property: Xinax\LaravelGettext\Translators\Gettext::$session

### ISSUE THREAD

**Issue by mixisLv** [xinax/laravel-gettext#103]
PHP: 7.0.12

Config:
   ` 'handler' => 'gettext'`

Got error:

> ErrorException in Gettext.php line 92: Undefined property: Xinax\LaravelGettext\Translators\Gettext::$session
> 
>     in Gettext.php line 92
>     at HandleExceptions->handleError('8', 'Undefined property: Xinax\LaravelGettext\Translators\Gettext::$session', '\vendor\xinax\laravel-gettext\src\Xinax\LaravelGettext\Translators\Gettext.php', '92', array('config' => object(Config), 'adapter' => object(LaravelAdapter), 'fileSystem' => object(FileSystem))) in Gettext.php line 92

**Comment by Anahkiasen** [comment]
Same issue here
