### ISSUE TITLE
[SOLVED] [Question] gettext:update doesn't see my strings

### ISSUE THREAD

**Issue by andreich1980** [xinax/laravel-gettext#105]
I have some strings in my `resources/views/layouts/app.blade.php`. 
They look like:
```
{{ __('Logout') }}
{{ __('Dictionaries') }}
```

I run `php artisan gettext:create` and it creates folders for locales I set up in config (en_US, ru_RU).
Next I run `php artisan gettext:update`, it says that 
```
PO file for locale: en_US/messages updated successfully
PO file for locale: ru_RU/messages updated successfully
Finished
2 locales updated.
```
but the file `resources/lang/i18n/en_US/LC_MESSAGES/messages.po` doesn't have any strings to translate. Neither does ru_RU file.
There's only header stings about these files. No string to translate.

Help me please.

**UPD**
The same problem with strings in controllers. 
I have a method of my controller `app/Http/Controllers/TopicsController.php`
```
public function destroy(Topic $topic)
{
    return __('Deleted');
}
```

After `php artisan gettext:update` I don't see the string in locale files.

What am I missing?

**UPD2**
I have disabled php-gettext extensiton in php.ini `;extension=php_gettext.dll`
Nothing is changed.

**Comment by andreich1980** [comment]
The same problem with strings in controllers. 
I have a method of my controller `app/Http/Controllers/TopicsController.php`
```
public function destroy(Topic $topic)
{
    return __('Deleted');
}
```

After `php artisan gettext:update` I don't see the string in locale files.

What am I missing?

**Comment by andreich1980** [comment]
I have disabled php-gettext extensiton in php.ini `;extension=php_gettext.dll`
Nothing is changed.

**Comment by andreich1980** [comment]
Shame on me, I haven't read the docs carefully. Works as described, PoEdit extracts strings from files.

**Comment by KasperFranz** [comment]
can you for good measure close the issue ;)?
