### ISSUE TITLE
Not compatible with Laravel 5.4

### ISSUE THREAD

**Issue by CedNet** [xinax/laravel-gettext#110]
Hi! I'm using your package and wanted to upgrade to Laravel 5.4 that just released. There's a change where the app->share() method has been removed and instead you should use singleton(). I cannot myself make a PR as I don't know how to fix it. I'm hoping you can :)

    LaravelGettextServiceProvider.php
    $this->app['laravel-gettext'] = $this->app->share(function ($app) use ($configuration) {

**Comment by lukashovancik** [comment]
fix <code>$this->app['laravel-gettext'] = $this->app->singleton('laravel-gettext',function ($app) use ($configuration) </code>

**Comment by Sb8691** [comment]
Hi guys! For Laravel 5.4. package needs to be updated. As @lukashovancik says! It's important!

**Comment by Belphemur** [comment]
Since I don't have any answer from the main developer.

I made a fork and published it on Packagist: 
https://packagist.org/packages/belphemur/laravel-gettext

The tag 5.0.0 is for laravel 5.4, tested and working.

**Comment by UriLucioWald** [comment]
Hi guys!
in Laravel 5.3 everything work smoothly , 
now in Laravel 5.4 I have change to  `$this->app->singleton('laravel-gettext',function ($app) use ($configuration) `
But now I am getting a RuntimeException A facade root has not been set.
when calling `\LaravelGettext::setLocale("en_US");`
All the files are exactly the same as 5.3.
Thanks

**Comment by saidbakr** [comment]
I have issues with 5.4 too.

**Comment by redalpha01** [comment]
@UriLucioWald and @saidbakr I strongly suggest you use @Belphemur 's package

**Comment by saidbakr** [comment]
@redalpha01 I used it. However, I could not able to get the translation text directly. I used it to update messages strings in the storage. then using poedit scanning storage messages files, then translate them, after that using a po to json converter I got .json file, finally I use laravel's native localization.

**Comment by redalpha01** [comment]
@saidbakr  did you uodate your laravel gettext config file appropriately to add the new _i() helper?

**Comment by spout** [comment]
Seems to be dead package ? Should we switch to @Belphemur package ?

**Comment by redalpha01** [comment]
@spout it's what I do

**Comment by Rellix999** [comment]
@Belphemur thanks, works as intended.
