### ISSUE TITLE
Gettext in Console / Commands?

### ISSUE THREAD

**Issue by CedNet** [xinax/laravel-gettext#113]
Hi! I just stumpled upon the fact that this Gettext package doesn't translate stuff ran via the artisan schedule:run and any command there. Also not for phpunit tests. 

Is there any way to force this package to load always no matter starter?

**Comment by dnmarques** [comment]
+1, Cannot translate emails that are sent with a command.

Does anyone knows how to solve this?

**Comment by tflori** [comment]
7 month and no answer? seems we have to solve our problems by our own...

**Comment by dnmarques** [comment]
@tflori Yep.. I moved already to belphemur/laravel-gettext because this package is not compatible with my version of Laravel.
