### ISSUE TITLE
Only works with two languages

### ISSUE THREAD

**Issue by nivv** [xinax/laravel-gettext#114]
I've just setup this package. I have a bunch of languages, but to reproduce you only need 3.

When the language is changed via the `LaravelGettext::setLocale('sv_SE')` and then again to `LaravelGettext::setLocale('en_GB')` and then finally to `LaravelGettext::setLocale('de_DE')` the displayed language will show up as `sv_SE` which is the fallback language.

If I call `Artisan::call('cache:clear');` before every locale-change it works as expected.

Is this expected behaviour?

I'm using Laravel v5.3.*

**Comment by redalpha01** [comment]
Could we see your resources/lang directory file tree?

**Comment by nivv** [comment]
Sure thing! Wasn't sure what you needed to see.

They are located in `resources/lang/i18n/`

![image](https://cloud.githubusercontent.com/assets/4033930/23135445/f90b97cc-f798-11e6-810e-dd0a3de6fd2c.png)

**Comment by redalpha01** [comment]
It's what I was afraid of, you don't have any compiled .mo files.

**Comment by redalpha01** [comment]
Open your translation in poedit and when saving it'll create the .mo file

**Comment by nivv** [comment]
@redalpha01 I have compiled `.mo`-files in the `de_DE` and `en_GB`. Am I missing something?

**Comment by nivv** [comment]
I'm using Redis as the cache engine and I checked the monitor.

```
1487662559.872633 [0 127.0.0.1:56972] 
"SETEX" "laravel-optigrip:pw5NEnMfjEnPfQAOcMQ25aTR3pJWNvQY65pvHZfs" "7200" 
"s:335:\"a:6:{s:30:\"laravel-gettext-localex-locale\";s:5:\"en_GB\";s:6:\"_token\";s:40:\"YJvCUMSfNz69t5lPLKw15EqYjaShM9dFBr3HYcA0\";s:6:\"locale\";s:2:\"de\";s:9:\"_previous\";a:1
:{s:3:\"url\";s:25:\"http://optigrip.dev/prods\";}s:6:\"_flash\";a:2:{s:3:\"old\";a:0:{}s:3:\"new\";a:0:{}}s:9:\"_sf2_meta\";a:3:{s:1:\"u\";i:1487662559;s:1:\"c\";i:1487662549;s:1:\"l\";s:1:\"0\";}}\";"
```

**Comment by nivv** [comment]
I've created a middleware and now it works as expected.

Handle-function

```php
<?php

public function handle($request, Closure $next)
{
    \LaravelGettext::setLocale(\Localization::getCurrentLocaleRegional());
    return $next($request);
}
```

Note:
_I'm using [mcamara/laravel-localization](https://github.com/mcamara/laravel-localization) in conjunction with this package_
