### ISSUE TITLE
Why LaravelGettext::setLocale($locale); doesn't change language in runtime and needs the server to be restarted? There is a workaround?

### ISSUE THREAD

**Issue by Konstantinos-infogeek** [xinax/laravel-gettext#116]
I store the user language preference to the database and i am using the **AppProvider** to get the stored preference and **set the Gettext locale**, but it doesn't change, unless i restart the server. **I haven't try it on the server online yet.** I tried with laravel build in server and my local installation of apache. I get the same result. Server must be restarted to change the language.

**Comment by crcms** [comment]
At the moment I have encountered the same problem

**Comment by dnmarques** [comment]
I know this is an old thread, but I was having this issue and I fixed it changing de fallback-locale on the config file.
