### ISSUE TITLE
Empty .PO Files

### ISSUE THREAD

**Issue by felipefreitasweb** [xinax/laravel-gettext#117]
Hello, 

A few days ago I'm trying to generate translation files from my laravel (5.3) but the files are always empty.
I followed all the installation processes, and there was no error.

**my config/laravel-gettext.php**
http://www.writeurl.com/text/auoor7j4vt9fsinbu6zf/7cj36bo0kmak0jvkxu7n

**When running php artisan gettext:update**
```
PO file for locale: en_US/messages updated successfully
PO file for locale: pt_BR/messages updated successfully
Finished
2 locales updated.
```
**When I open a .po file (resources/lang/i18n/en_US/LC_MESSAGES/messages.po OR resources/lang/i18n/pt_BR/LC_MESSAGES/messages.po)**
http://www.writeurl.com/text/e0c0lky3id6rc0m7ia8d/jovpv494s76iccyqp8g8

**locale -a**
http://www.writeurl.com/text/167y4l9dq6v2trhithfq/ev5wmcyeliuxwoballtx

**Server Details**
`CENTOS 7`
`Linux ip-172-31-10-239.ec2.internal 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
```
PHP 7.0.17 (cli) (built: Mar 14 2017 15:14:30) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

Could you please help me? (I do not know what else to do)
If you need more information let me know.

Thanks and sorry for my english :D

**Comment by mattrabe** [comment]
Hi @felipefreitasweb - I have found that the process of getting phrases into the po files is a two-step process:

1. Run `php artisan gettext:update`. This command converts phrases from blade templates (which gettext/Poedit cannot parse) into parseable phrases, and stores them in files in /storage/framework/messages
2. Open the po file in Poedit and run Catalog->Update from Sources. This will parse everything (which if you take a look at Catalog->Properties->Source Paths you will find includes /storage/framework/messages) and pulls in the phrases into the po file.

Skipping either step results in not pulling in phrases from Blade templates.

**Comment by felipefreitasweb** [comment]
Perfect!
I simply pointed to the /storage/framework/messages folder and solved problem.

Thanks!
