### ISSUE TITLE
Plural support? Like _n() ??

### ISSUE THREAD

**Issue by canfiax** [xinax/laravel-gettext#16]
Do you support this?

**Comment by shaggyz** [comment]
Hi, yes, I think. It is supported by the php-gettext module: http://php.net/manual/en/function.ngettext.php. Let me know if the package have something to do with this.

Cheers!

**Comment by canfiax** [comment]
Sorry - got confused. Of course ngettext is the right option.

**Comment by markoheijnen** [comment]
Isn't the reason someone wants to use this package because of the easy replacements? so I would have expected _n. Maybe even _x for strings with context but that is something gettext implementation in PHP is lacking (pgettext).
