### ISSUE TITLE
Create .po file for all languages

### ISSUE THREAD

**Issue by markushausammann** [xinax/laravel-gettext#18]
Hi, thanks for the great package, installation works like a charm. I love to work with gettext, it's my translation backend of choice or all frameworks and apps.

I think there is one problematic aspect in your approach. You don't create a po file for the default language. I think that's a mistake. If you have a po file for the default language too, you can correct small mistakes or even re-arrange a sentence without the need to adjust the translations into all other languages. You shouldn't have to go and edit actual language strings in the source code if they're not changing completely. Therefore `php artisan gettext:create` should include creating a po file for the default language too.

**Comment by shaggyz** [comment]
Sí, definitivamente sería muy útil tener esta funcionalidad. Cuando tenga tiempo liberaré una versión con esto. Thank you.

**Comment by shaggyz** [comment]
Yes, definitely would be very useful to have this functionality. When I have time I will release a version with this. Thank you.

**Comment by younes0** [comment]
+1 
So I'm not the only one in this case :)

**Comment by shaggyz** [comment]
@younes0 definitely, he problem is I have not enough time this week :cry:

**Comment by younes0** [comment]
@shaggyz no worries, we can also make PR

**Comment by shaggyz** [comment]
That would be great. Thank you guys.

**Comment by shaggyz** [comment]
Feature released on 2.0.3.

**Comment by younes0** [comment]
+1
