### ISSUE TITLE
Code examples don't work in Larave l5

### ISSUE THREAD

**Issue by markushausammann** [xinax/laravel-gettext#19]
For example

    public function changeLang($locale=null)
    {
        LaravelGettext::setLocale($locale);
        return Redirect::to(URL::previous());
    }

should use

    return redirect()->back();

instead.

**Comment by shaggyz** [comment]
This is working fine on L5: 
```
return Redirect::to(URL::previous()); 
```

**Comment by markushausammann** [comment]
Not in my case.

**Comment by shaggyz** [comment]
Are you using Laravel 5.0.*?

**Comment by markushausammann** [comment]
Yes.

**Comment by markushausammann** [comment]
It's not a problem for me because the other way works, I just wanted to let you know .

**Comment by shaggyz** [comment]
It's strange, because I have almost 30 sites with the same laravel version and package, working with this code. Please share the error that returns this:

```php
return Redirect::to(URL::previous()); 
```

Thank you!

**Comment by markushausammann** [comment]
Sorry, my bad, it was just missing `use` statements for the Facades.
