### ISSUE TITLE
Translation not shown

### ISSUE THREAD

**Issue by markushausammann** [xinax/laravel-gettext#20]
And finally, everything is set up but unfortunately, strings are not translated. :(

**Comment by shaggyz** [comment]
Check your setup, it is working.

**Comment by markushausammann** [comment]
Well no, it isn't.

**Comment by markushausammann** [comment]
But honestly, I did everything exactly according to the readme. My translation mo and po files exist, translations were parsed and translated in poEdit, the language switcher works, setting the locale works but the translations are NOT shown.

**Comment by markushausammann** [comment]
Can you tell me where in the code the po file is loaded so I can set a breakpoint there?

**Comment by shaggyz** [comment]
Check this: https://github.com/xinax/laravel-gettext/blob/master/src/Xinax/LaravelGettext/Gettext.php (this is the gettext wrapper) and this: http://php.net/manual/es/book.gettext.php

Also, the other closed issues might help you. Good luck!

**Comment by markushausammann** [comment]
I don't see the line where the po file is actually loaded?

**Comment by shaggyz** [comment]
Cause this is an internal task of the **php-gettext** module. This package is just a wrapper to work with Laravel. This probably means that you have a problem with the **gettext** module.

**Comment by markushausammann** [comment]
I think so too but it might be the way the wrapper is written, it works with apache but not with nginx. I'll have to look into it... :/

**Comment by markushausammann** [comment]
phpinfo() shows that gettext is enabled with nginx... but still not working.

**Comment by markushausammann** [comment]
It seems it's actually a thing with Ubuntu: http://pof.eslack.org/2010/11/17/php-gettext-problems-on-ubuntu-server/ maybe that's going to solve it.

**Comment by markushausammann** [comment]
Nothing helps. Seems nginx, ubuntu and gettext don't get along very well.

**Comment by markushausammann** [comment]
After another restart of nginx and deleting compiled views in laravel, it finally works.

**Comment by markushausammann** [comment]
Seems that on CentOS with Apache it doesn't work properly either. Now that I read this http://stackoverflow.com/questions/3398113/php-gettext-problems I'm thinking I'll just go for PHP arrays or try to port Zend Translate to Laravel.

**Comment by rpsimao** [comment]
The same happens in Homestead. It doesn´t work. When using the PHP built in webserver in OS X, it work perfectly. That's a shame, but I´ll have to ditch Homestead.....

**Comment by canfiax** [comment]
I have the same issue here: https://github.com/xinax/laravel-gettext/issues/60

@markushausammann  what was your final solution? Using PHP arrays, or did deleting compilde views in laravel + restart solve the issue? I have cleared cache several times + restart, but when I hit refresh, translations are back to fallback language (i.e. en_US).

**Comment by markushausammann** [comment]
@canfiax I think I gave up, don't know how I solved it. Probably by not using gettext.

**Comment by cadr-sa** [comment]
An easy way to fix the issue 

to have gettext functions working in ubuntu server you need to add the proper locales to the system first, for example, to translate text in spanish:

# sudo -s
# cat /usr/share/i18n/SUPPORTED |grep -i "es_ES" > /var/lib/locales/supported.d/es

And repeat for every language you need… :)

when finished, run dpkg-reconfigure locales and you are done!
