### ISSUE TITLE
Poedit not finding with blade

### ISSUE THREAD

**Issue by KasperFranz** [xinax/laravel-gettext#25]
Hey when i do 
    {{ _('Translated string') }}
Poedit doesn't seem to find the string but if i do 
<?=_('Translated string') ?>  it catches the string, where/what can i do so it catches _('Text') inside of blade?

**Comment by shaggyz** [comment]
Try ./artisan gettext:update It re-compiles blade views

**Comment by KasperFranz** [comment]
That seems like awefull lot of un needed code, isn't there another way to get poedit to reconize it?

**Comment by shaggyz** [comment]
Nope, but ./artisan gettext:update is a command. Blade views are working fine, you just need to compile it, since it are not supported by poedit.

**Comment by zodman** [comment]
relate to https://github.com/xinax/laravel-gettext/issues/49
