### ISSUE TITLE
Working with packages and templates

### ISSUE THREAD

**Issue by Truemedia** [xinax/laravel-gettext#26]
Hi, I found this project recently and really appreciate the effort that has gone into it.

At the moment I have several packages which currently have PO files which extracts strings form handlebars templates inside the relevant package views directory.

I have an extractor in poedit for this and that works great aswell, and handlebars templates are being parsed as regular views, but I'm not sure how to integrate this package in my setup.

It is possible to declare template functions for handlebars but I'm not sure what I would have to include from this library to make that work, and currently if I add my view directory to the gettext source-paths array it won't pick up the strings in my templates (I'm assuming because of the extension).

I would appreciate any suggestions, or be willing to contribute to this project if I find something useful myself.

**Comment by shaggyz** [comment]
Hi! If your templates are in blade format you need to run ```./artisan gettext:update``` before, since the blade views need to be compiled.

Poedit doesn't work with blade files directly.

Regards!

**Comment by Truemedia** [comment]
Thanks I'll start my search from their to integrate handlebars (blade no good for me, too limited).

I can already see a compileViews method which you use to compile the blade templates into PHP files, but is it maybe worth allowing other packages to hook into that functionality? I already have my own package which compiles handlebars to PHP files which could be altered.

**Comment by shaggyz** [comment]
Well, i never used handlebars, but you always can override the compileViews method and add handlebars support, exactly like you said. Be sure to add the output paths of your compilers to the 'source-paths' configuration key.

Good luck!
