### ISSUE TITLE
Not finding calls _ () and generates aquivo blank

### ISSUE THREAD

**Issue by meneguite** [xinax/laravel-gettext#29]
Hello guys, I'm trying to make use of this package has a few days to no avail. I followed the instructions but the files are generated, but no content.

I had to make some adjustments to use it in laravel 5.1, below:
From:        'Xinax\LaravelGettext\LaravelGettextServiceProvider',
For:           Xinax\LaravelGettext\LaravelGettextServiceProvider::class,

From:        'Xinax\LaravelGettext\Middleware\GettextMiddleware',
For:            \Xinax\LaravelGettext\Middleware\GettextMiddleware::class,

My configuration file: https://gist.github.com/meneguite/895325e313a5791df537

The whole folder structure is generated but the files do not, but if I create the files manually "messages.po" the process begins apparently run smoothly.

After the generated file manually, and run the command "php artisan gettext: update" is passed me the following message:
PO file for locale: pt_BR/messages were updated successfuly
PO file for locale: en_US/messages were updated successfuly
Done!
2 locales were updated.

And the following content is included in the file before blank:
https://gist.github.com/meneguite/3550b82617c0172565e6

I am in great need of using this package, I'm still starting at laravel and this package is escencial for my migration to this framework.

Already I put myself at the disposal if you need more information.

**Comment by meneguite** [comment]
Good evening, I managed to isolate the problem ... apparently must be something with the blade, the string I put the controller or even the view that put in php format it (<?php ?>) are located correctly. but calls {{_ ('string')}} does not work. I will continue testing to see if I can identify the problem.

**Comment by shaggyz** [comment]
Hi, sorry for the delay (we are deploying a huge project, this month). Blade views need to be compiled for poEdit (poedit needs plain php files). You need to run **artisan gettext:update** everytime you change blade views, then you can open files in poedit and see the changes.
