### ISSUE TITLE
Error when run: php artisan gettext:create

### ISSUE THREAD

**Issue by EssamWD** [xinax/laravel-gettext#30]
Hi,

I'm using the version 2.x with laravel 5.1, when I run php artisan gettext:create it's return this error:

"vendor/symfony/finder/Finder.php:677 - The "" directory does not exist."

and when I go to "lang" path it's created all this 3 directions "i18n/en_US/LC_MESSAGES" but the "LC_MESSAGES" folder is empty and no .po files is created.

Thanks,
Essam

**Comment by shaggyz** [comment]
Hi! 5.1 is not supported, yet.

**Comment by shaggyz** [comment]
Supported on 3.0.1.
