### ISSUE TITLE
messages directory creates .php files in all cases, causes problems with IDE netbeans

### ISSUE THREAD

**Issue by sdwarwick** [xinax/laravel-gettext#32]
netbeans wants to find all of the syntax errors in files, and flag those that are incorrect.  apparently,  javascript files ( *.js) show up as .php files in the messages directory and mess up the netbeans syntax handling perhaps the messages files could be written without the .php extension, like the other cache directories?

**Comment by shaggyz** [comment]
Certainly, that's not possible, since PoEdit looks only *.php files by default. 
I think it's a IDE issue. I do not use Netbeans, but i guess it must have an "ignore directory" function, like other similar tools. Good luck!
