### ISSUE TITLE
Translated test not showing

### ISSUE THREAD

**Issue by N-Molham** [xinax/laravel-gettext#39]
Hello,
I tried your package and implemented it correctly and the localization changes fine and saved in the session but the translated test not showing and shows the original text like there is no translation for it.
How can I debug the data workflow to figure out where is the problem ?

**Comment by ihoru** [comment]
I've met the same problem.
In my case I had to install locally this locale: es_AR

**Comment by N-Molham** [comment]
@ihoru do you mean to fix it ? or what exactly ?

**Comment by ihoru** [comment]
@N-Molham, It's my fault - I didn't understand you first time.

So, lets try from the beginning :)
Did you generate messages.**po** file and create messages.**mo** file with translations?

**Comment by N-Molham** [comment]
Yep, and those are the files > https://drive.google.com/folderview?id=0B2pwLeWWR6mHVmdncGpINUJJTDA&usp=sharing they are localized for Arabic "ar_EG"

**Comment by ihoru** [comment]
Are you  sure "ar_EG" locale is activated while trying?

**Comment by N-Molham** [comment]
Yep, in the `laravel-gettext.php` file located in the `config` dir
```
return [
	'locale' => 'en_US',
	'supported-locales' => [
		'en_US',
		'ar_EG',
	],
	'encoding' => 'UTF-8',
    'translations-path' => '../resources/lang',
	'fallback-locale' => 'en_US',
	'domain' => 'messages',
	'source-paths' => [
        'Http/Controllers',
        '../resources/views',
        'Commands'    
	],
	'sync-laravel' => true,
];
```

**Comment by ihoru** [comment]
Try to call this:
\LaravelGettext::setLocale('ar_EG');
dd(_('Enroll Now'));

**Comment by N-Molham** [comment]
I tried :smile: 
```
get( '/test', [ 'as' => 'profile', 'uses' => function() {
	\LaravelGettext::setLocale( 'en_US' );
	dump( \LaravelGettext::getLocale(), _( 'Read Now' ) );

	\LaravelGettext::setLocale( 'ar_EG' );
	dump( \LaravelGettext::getLocale(), _( 'Read Now' ) );
} ] );
```
both output 'Read Now' ... and that phrase is translated

**Comment by ihoru** [comment]
Please execute this command:
locale -a | grep ar_EG

**Comment by N-Molham** [comment]
it's a unix command, I am running windows 10 ... can you give me the alternative to windows ?

**Comment by ihoru** [comment]
Sorry, I cannot help you with this. You should check weather that locale is installed in your operation system.

**Comment by N-Molham** [comment]
yep, Arabic (Egypt) is installed on my system

**Comment by JVMartin** [comment]
Just to reinforce:

I had the same issue, with Spanish not displaying, until I did:
```
sudo locale-gen es_ES.utf8
```

Now all is well.

**Comment by shaggyz** [comment]
@JVMartin Well, I think that could be added to the docs, since *you need the locales used by your application installed on system-wide*, and it's a very important part if you are not familiarized with GNU Gettext. 

On debian systems I do this in this way: ```dpkg-reconfigure locales```, but your command is better because applies to other linux distros. 

@N-Molham BTW this package never was tested on MS Windows, so some feedback on this topic would be appreciated. 

@ihoru You're right about package tests, some locales to run tests are required. Development documentation can be added if needed.

Thank you guys!

**Comment by shaggyz** [comment]
BTW, PR are always very appreciated! :sake:

**Comment by N-Molham** [comment]
@shaggyz it just simply not working ... even if I instated gettext binaries for windows

**Comment by JVMartin** [comment]
@N-Molham Are you sure you're binding your text domain files properly?

Look at this line:
https://github.com/xinax/laravel-gettext/blob/master/src/Xinax/LaravelGettext/Gettext.php#L188

And then look at how other ppl have somehow managed to get GNU gettext to work on windows:
http://stackoverflow.com/a/10611614/1946395

**Comment by N-Molham** [comment]
I think file binding is correct as the same application with same file
structure runs on Ubuntu with apache with no problem

**Comment by JVMartin** [comment]
gettext works completely differently on Windows than it does on Linux.  (As with most things, it works flawlessly on Linux straight out of the box but takes a shitload of tweaking to get to work properly on Windows.)

You should know that your domain files are in totally different locations on both systems.
