### ISSUE TITLE
messeges.po problem

### ISSUE THREAD

**Issue by tomoaki130** [xinax/laravel-gettext#42]
(Laravel5.1)
I did what README.md says, but after I made 
```
    php artisan gettext:update
```
command, It seems like it doesn't catch any word surrounded by _() tag.

and messeges.po is like the following.
```
msgid ""
msgstr ""
"Project-Id-Version: MultilanguageLaravelApplication\n"
"POT-Creation-Date: 2015-10-29 14:36+0000\n"
"PO-Revision-Date: 2015-10-29 14:36+0000\n"
"Last-Translator: James Translator <james@translations.colm>\n"
"Language-Team: James Translator <james@translations.colm>\n"
"Language: ja_JP\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.5.4\n"
"X-Poedit-KeywordsList: _\n"
"X-Poedit-Basepath: ../../../../../app\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Poedit-SearchPath-0: Http/Controllers\n"
"X-Poedit-SearchPath-1: ../resources/views\n"
"X-Poedit-SearchPath-2: ../storage/framework/messages/\n"
```

I think messages.po should have words surrounded by _() tag so that we can translate them in PoEdit later.

Does anyone have the same problem or know any solution? 

Thanks in advance.

**Comment by ihoru** [comment]
It's expected situation. You should open with poedit this file and click there "Update" button.

**Comment by tomoaki130** [comment]
Thank you for your reply, ihoru.

I misunderstood how it works.

I translated some sample sentences.
and my Po file became like the following.

```
msgid ""
msgstr ""
"Project-Id-Version: MultilanguageLaravelApplication\n"
"POT-Creation-Date: 2015-10-30 21:53+0900\n"
"PO-Revision-Date: 2015-10-30 21:55+0900\n"
"Last-Translator: James Translator <james@translations.colm>\n"
"Language-Team: James Translator <james@translations.colm>\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.8.6\n"
"X-Poedit-KeywordsList: _\n"
"X-Poedit-Basepath: ../../../../../app\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Poedit-SearchPath-0: Http/Controllers\n"
"X-Poedit-SearchPath-1: ../resources/views\n"
"X-Poedit-SearchPath-2: ../storage/framework/messages\n"

#: ../resources/views/welcome.blade.php:42
#: ../storage/framework/messages/441aef21be6c3c32079f86e5812a9d0a.php:42
msgid "言語テスト"
msgstr "language test chinese"

#: ../storage/framework/messages/441aef21be6c3c32079f86e5812a9d0a.php:43
msgid "name"
msgstr "name dayo chinese"

#: ../storage/framework/messages/441aef21be6c3c32079f86e5812a9d0a.php:44
msgid "最後の文"
msgstr "last sentence chinese"

```

It seems like I translated words inside files in ../storage/framework/messages/ instead of files in the Views..
Is this supposed to happen?

**Comment by ihoru** [comment]
It's normal situation.
This library generates php files for it self.

**Comment by shaggyz** [comment]
Hi @tomoaki130, as @ihoru (and docs XD) says:

> PoEdit doesn't "understand" blade syntax. When using blade views you must run php artisan 
> gettext:update in order to compile all blade views to plain php before update the translations in PoEdit

Compiled files are stored temporarily in storage folder (the default in laravel for this kind of tasks)

**Comment by tomoaki130** [comment]
I think I understand how it works, and I am glad what I am doing is on the right path.

Thank you guys! @shaggyz @ihoru
