### ISSUE TITLE
Laravel Controller

### ISSUE THREAD

**Issue by paper9oll** [xinax/laravel-gettext#44]
Hi developer,

i follow your documentation not how to implement but i get this error

Class 'takebee\Http\Controllers\LaravelGettext' not found.

**Comment by Nikolajpetersen** [comment]
Hi @paper9oll,

That is because you need to use the LaravelGettext.

Example:

```php
<?php

namespace takebee\Http\Controllers;

use LaravelGettext;

class Controller
{

}
```

**Comment by paper9oll** [comment]
alright thanks you
