### ISSUE TITLE
Config for X-Poedit-KeywordsList

### ISSUE THREAD

**Issue by Gummibeer** [xinax/laravel-gettext#45]
It would be nice to have a config for the Keywordlist of PoEdit.

This will help to use custom translation methods in addition to the single standard one. For example, this is the WordPress one:

> X-Poedit-KeywordsList: __;_e;__ngettext:1,2;_n:1,2;__ngettext_noop:1,2;_n_noop:1,2;_c,_nc:4c,1,2;_x:1,2c;_ex:1,2c;_nx:4c,1,2;_nx_noop:4c,1,2;\n

If you want to extend the gettext by some features there is no way around custom helper functions but they also should get translated and recognized by PoEdit.

**Comment by shaggyz** [comment]
That would be great, it can be added as a new configuration option to apply right here: https://github.com/xinax/laravel-gettext/blob/master/src/Xinax/LaravelGettext/FileSystem.php#L170 
Do you think that same list used in wordpress can be the default value for this option?

**Comment by Gummibeer** [comment]
To just transfer it wouldn't solve it - there are a lot of wordpress related functions but just create an option like and let the developers add their own functions would be nice.

```php
'keywordslist' => [
      '_',
],
```

**Comment by shaggyz** [comment]
ok! it will be added!

**Comment by Gummibeer** [comment]
Thanks, this will help a lot - and just for interest: why are you using the native php gettext? It just causes a lot of problems: every locale has to be installed on the server, after every deploy/change the php & webserver have to be restarted and so on. It's just a pain to work with it!

We wrote a Singleton including caching for the Symfony Translation Package. It's much easier to work with this cause a simple clear:cache is enough to get all the new translations and no webserver restarts are required.

```php
<?php
namespace Cali\Libs;

use Symfony\Component\Translation\Loader\PoFileLoader;
use Symfony\Component\Translation\Translator as SymfonyTranslator;

class Translator
{
    private static $instance;

    private function __construct() {}
    private function __clone() {}

    public static function getInstance()
    {
        if (null === self::$instance) {
            self::$instance = self::createInstance();
        }
        return self::$instance;
    }

    protected static function createInstance()
    {
        if (config('app.debug') && !env('NEVER_FORGET_CACHE', false)) {
            \Cache::forget('po_cache');
        }

        return \Cache::rememberForever('po_cache', function () {
            $basePath = 'resources/lang/i18n';
            $locales = [
                'de_DE',
                'en_US',
            ];

            $translator = new SymfonyTranslator(config('app.locale'));
            $translator->addLoader('po', new PoFileLoader());
            $translator->setFallbackLocales([config('app.locale')]);
            foreach ($locales as $locale) {
                $path = base_path($basePath . DIRECTORY_SEPARATOR . $locale . DIRECTORY_SEPARATOR . 'LC_MESSAGES');
                $file = $path . DIRECTORY_SEPARATOR . 'messages.po';
                if (file_exists($file)) {
                    $translator->addResource('po', $file, $locale);
                    $translator->getCatalogue($locale);
                }
            }
            return $translator;
        });
    }
}
```

It's mostly based on your po file generation.

**Comment by tgustinak** [comment]
Will this change (custom keywords) be implemented soon? Do you need any help with this? :)

**Comment by shaggyz** [comment]
Config for X-Poedit-KeywordsList added on 3.1.1 (https://github.com/xinax/laravel-gettext/releases/tag/3.1.1)
