### ISSUE TITLE
Not working when executing php artisan serve

### ISSUE THREAD

**Issue by christianesperar** [xinax/laravel-gettext#46]
Gettext not translating the keys when executing php artisan serve or php -S localhost:8000

**Comment by shaggyz** [comment]
Initial support is for apache, I don't know how php modules are managed with the laravel integrated web server, but the php-gettext module must be loaded and working.
The integrated server must be loading modules from the CLI php instance, but i'm not sure.
Check this and please provide more details about this issue if persists.

**Comment by ihoru** [comment]
@shaggyz, built-in php server and laravel-gettext works great for me! So it should work.

**Comment by shaggyz** [comment]
@ihoru Thanks for the feedback.

**Comment by christianesperar** [comment]
I noticed that it's working on Mac but not working on Ubuntu (maybe on all Linux Distro).

**Comment by ihoru** [comment]
I use Ubuntu as well, and it works fine for me.

**Comment by shaggyz** [comment]
Tested on OSX 10.* and many linux distributions like: Debian, Ubuntu, Fedora, etc. Please provide some info like your configuration values, laravel logs. Package is working.
