### ISSUE TITLE
undefined function bindtextdomain

### ISSUE THREAD

**Issue by salim-dev** [xinax/laravel-gettext#53]
Hello
I have a problem, I displayed:

FatalErrorException in Gettext.php line 194:
Call to undefined function Xinax\LaravelGettext\bindtextdomain()

I use:
- Local = MAMP PRO =>  I have to activate : extension=php_gettext.dll
- Laravel  :  5.2.11
- package :  "xinax/laravel-gettext": "^3.0"

thank you kindly help me

**Comment by salim-dev** [comment]
package : "xinax/laravel-gettext": "3.1.x"

**Comment by shaggyz** [comment]
Hi, sorry for the delay, it seems like you dont have the mod_gettext loaded. Is activated? Yoy can see this in ```phpinfo()``` output.

**Comment by salim-dev** [comment]
I have solved the problem, thank you

**Comment by lk22** [comment]
i have the same issue but while running CircleCi Builds

is there any solution for enabling that module on its php.ini file?

help is appreciated :)

**Comment by shaggyz** [comment]
Yes, you need the php-gettext extension installed: http://php.net/manual/en/gettext.installation.php
And added to your php.ini:
```
extension=gettext.so
```
Check the CircleCi docs to add php extensions: https://circleci.com/docs/language-php/#dependencies
Regards.

**Comment by lk22** [comment]
sry for the bothering, 

but adding: extension=gettext.so to my local php.ini file?
or is there a way to enable the adda extension=gettext.so to the circleci build through the circle.yml file ? 
and gettext is installed through my composer.json

thanks for the help :)

**Comment by faizannoor** [comment]
Yes add it it /etc/php.ini
