### ISSUE TITLE
load  translations from multiple folders

### ISSUE THREAD

**Issue by mohamedsharaf** [xinax/laravel-gettext#54]
Open the PO file for the language that you want to translate with PoEdit. The PO files are located by default in resources/lang/i18n/[locale]/LC_MESSAGES/[domain].po. If you have multiple gettext domains, one file is generated by each domain.

as listed in documentation po files loading from 
resources/lang/i18n/[locale]/LC_MESSAGES/[domain].po

what if i have modules and need to load files for every module

say 
app/modules/Modulename/lang/i18n/[locale]/LC_MESSAGES/[domain].po
app/modules/news/lang/i18n/[locale]/LC_MESSAGES/[domain].po

in config there is 
    'translations-path' => '../resources/lang',

can this be 

    'translations-paths' => [ '../resources/lang',
'another_path',
],

also is there is  handler for this like function $translator->addTranslationsdirectory

**Comment by shaggyz** [comment]
Hi, when you say "module", you mean an independent laravel project or a custom directory structure in your laravel project? As you say, this package allows you to do that, but with files instead of directories. Please explain your case of use.

**Comment by mohamedsharaf** [comment]
say i have like this structure

-Modules
--News
----languages
--------news.php //this is the lang file i need to load
--Blog
----languages
--------blog.php //this is the lang file i need to load
--Cart
----languages
--------cart.php //this is the lang file i need to load

how to load all language files

**Comment by shaggyz** [comment]
Oh, this package follows the GNU/Gettext directory structure, so I think it doesn't fit with your needs.
