### ISSUE TITLE
Required header Plural-Forms is missing.

### ISSUE THREAD

**Issue by mixisLv** [xinax/laravel-gettext#56]
Your package does not create [Plural-Forms](http://poedit.net/trac/wiki/Doc/PluralForms) header.

**Comment by shaggyz** [comment]
Ok! for next release. Thank you.

**Comment by shaggyz** [comment]
Plural-Forms header added.

**Comment by mixisLv** [comment]
Where can I configure this option?

**Comment by shaggyz** [comment]
Oh, sorry, my bad, it's on development branch, issue open until 4.x release.
