### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Elbandi** [xinax/laravel-gettext#57]
I try to use this, but it doesnt work.

This is the steps i do:

> composer create-project --prefer-dist laravel/laravel blog
> composer require xinax/laravel-gettext "3.1.x"
> 

edited the resources/views/welcome.blade.php :
```
 {{ _("foo") }}
 <? echo _("bar"); ?>
 <?= _("baz"); ?>
```
After that i run:

> php artisan vendor:publish
> php artisan gettext:create
> 

and the _resources/lang/i18n/en_US/LC_MESSAGES/messages.po_ file just
has a header, but no msgid.
```
msgid ""
msgstr ""
"Project-Id-Version: MultilanguageLaravelApplication\n"
"POT-Creation-Date: 2016-02-10 13:20+0000\n"
"PO-Revision-Date: 2016-02-10 13:20+0000\n"
"Last-Translator: James Translator <james@translations.colm>\n"
"Language-Team: James Translator <james@translations.colm>\n"
"Language: en_US\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.5.4\n"
"X-Poedit-KeywordsList: _\n"
"X-Poedit-Basepath: ../../../../../app\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Poedit-SearchPath-0: Http/Controllers\n"
"X-Poedit-SearchPath-1: ../resources/views\n"
"X-Poedit-SearchPath-2: Console/Commands\n"
"X-Poedit-SearchPath-3: ../storage/framework/messages/\n"
```
I run this too, but still empty
> php artisan gettext:update

**Comment by shaggyz** [comment]
Post your details/versions about: os, laravel, webserver and php. Also, post the output of this command please:

```
locale -a
```

**Comment by thsantac** [comment]
Hi, 

I user Laravel 5.1 and just update my project to install laravel-gettext. 

My MAMP's phpinfo page shows that gettext is enabled.

I have updated all my controller scripts to add _() each time a string was encountered.

My po files are created in ressources/lang bu when I run update, they remains empty (just a header).

locale -a shows all supported languages (fr_FR, en_GB, en_US, it_IT, es_ES).

I wonder what should I do with GNU Gettext however...

Thanks for help :-)

**Comment by Elbandi** [comment]
ubuntu trusty, php5 from package (5.5.9+dfsg-1ubuntu4.14), latest laravel (fresh install), lighty webserver (but it is not used by php artisan :D )

```
# locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX

```

**Comment by thsantac** [comment]
Hi,
I had the same issue but after opening an empty po file and pressing update button in poedit all my strings were loaded :-)

**Comment by shaggyz** [comment]
As @thsantac says, you need to click update button on PoEdit, all strings will be collected then. This is how this package works. Sorry, I misunderstood your issue.

**Comment by mgarciadelojo** [comment]
@shaggyz I realized that, after doing it, no translations are showing but the original string passed to the _() function. how can I fix it?

**Comment by thsantac** [comment]
Usually, when loading the strings for the first time, no translations are shown because you have to enter it all manually (even if POEdit can helps in most cases).

**Comment by mgarciadelojo** [comment]
Hi @thsantac, 

Thanks for your quick reply! The issue was I had to install the language pack in spanish to get it working. The commands I run were:

```
sudo apt-get install language-pack-es
sudo dpkg-reconfigure locales
```

After that, everything worked fine!

Thanks again.
