### ISSUE TITLE
Translate routes i.e. /about-us in en_US and /om-os in da_DK

### ISSUE THREAD

**Issue by simplenotezy** [xinax/laravel-gettext#59]
How could that be possible?

**Comment by shaggyz** [comment]
Something like this may work (not tested):

```php
Route::get('/' . _('about-us'), function(){
    ...
});
```
Please let me know if it does

**Comment by canfiax** [comment]
If I have the following route:

		Route::get('/' . _('Classes'), function() {
			echo 'hi ' . _('Classes');
		});

I can only access it through "Classes", but when I hit the route, it will show the translated string of "Classes".

**Comment by ihoru** [comment]
You didn't change current locale before calling "Route::get".

**Comment by canfiax** [comment]
@ihoru true, but what does that change?

**Comment by canfiax** [comment]
True, following works:

		\LaravelGettext::setLocale('da_DK');
		Route::get('/' . _('Classes'), function() {
			echo 'hi ' . _('Classes');
		});

But I guess the way the package is setup is to be set through middleware, right?

**Comment by canfiax** [comment]
Translatable routes is something that could make this package really strong IMO. The biggest difficulity right now, as I see it, is a clean & proper way to translate routes, and the option to choose between two main setups:

    Setup 1 (prefix): http://domain.com/en/about-us
    Setup 2 (subdomain): http://en.domain.com/about-us

**With the posibility having the prefix/subdomain optional for the default language**: http://domain.com/about-us (for english).

This package is about it, regarding prefix: https://github.com/mcamara/laravel-localization but really lacks a posibility to have setup 2.
