### ISSUE TITLE
2.x branch not up to date?

### ISSUE THREAD

**Issue by KasperFranz** [xinax/laravel-gettext#63]
Shouldn't the 2.x branch be up to date with the 2.0.3 release :)?

**Comment by KasperFranz** [comment]
I did that in pr #68

**Comment by shaggyz** [comment]
Thank you, merged, but 1.x and 2.x are freezed. (you know: It's a PIA support laravel 4.x, 5.0 and 5.2.x and all of its structure changes) so we're focused on 3.x.

**Comment by KasperFranz** [comment]
I know :) 

Just wanted it to be up to date so it was easier to look at a later time :) and if someone wanted to make a PR for a feature to all the branches :)

**Comment by shaggyz** [comment]
You're right. I don't know why I forgotten to merge it.
