### ISSUE TITLE
Can I gitginore storage/framework/messages/* ?

### ISSUE THREAD

**Issue by canfiax** [xinax/laravel-gettext#69]
Everytime I run gettext:update I see a lot of files like this:

    storage/framework/messages/c0765d2cb7925273e7168e8901e2fac9654fa3b0.php.php

Can I delete thoose? I.e. add the whole folder `storage/framework/messages/**` to gitignore?

**Comment by KasperFranz** [comment]
yes 

see #55 for how it fix it. 

But you can also just add a messages/ to your gitignore

**Comment by shaggyz** [comment]
Yes, as @KasperFranz says, you can safely ignore this directory (used for blade views compilation)
