### ISSUE TITLE
Not working on Laravel 5.2 with Homestead 0.4.1

### ISSUE THREAD

**Issue by morfin** [xinax/laravel-gettext#71]
OS Specs:
```
PHP:
PHP 7.0.1-1+deb.sury.org~trusty+2 (cli) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0RC3, Copyright (c) 2002-2015, by Derick Rethans

Nginx:
nginx version: nginx/1.9.7
```

Problem: Strings are not translated.

I Restarted the server (service nginx restart), ran php artisan cache:clear. I even did vagrant halt / up.

The locale is actually setting up correctly in session. 

\LaravelGettext::getLocale() is giving the correct locale.

1.- po and mo files correctly generated in place.
2.- I was able to translate strings with PoEdit.
3.- I can set the locale with \LaravelGettext::setLocale() and it is persisted in session. 
4.- I installed locale on system: sudo apt-get install language-pack-pt-base
5.- Be sure locale is up-to-date: sudo locale-gen pt

Notice that I'm using Portuguese (pt)

If I echo:
_('This is a test');

I get "This is a test" instead of "Isto é um teste". 

So in order to test if gettext is actually working at its core level with homestead, I put these lines on public/index.php, before laravel runs:

```
$directory = dirname(__FILE__).'/../resources/lang/i18n';
$domain = 'messages';
$locale ="pt-BR.utf8"; // also tried with: $locale ="pt-BR";
putenv("LANG=".$locale); // Without this, translation doesn't work, even if setlocale() finds the locale.
setlocale(LC_MESSAGES, $locale);
bindtextdomain($domain, $directory);
textdomain($domain);
bind_textdomain_codeset($domain, 'UTF-8');

echo _('String to be translated.'); exit;
```

The File structure:
```
resources
├── assets
│   └── sass
│       └── app.scss
├── lang
│   ├── en
│   │   ├── auth.php
│   │   ├── pagination.php
│   │   ├── passwords.php
│   │   └── validation.php
│   ├── es
│   │   └── validation.php
│   └── i18n
│       ├── pt_BR
│       │   └── LC_MESSAGES
│       │       ├── messages.mo
│       │       └── messages.po
│       └── en_US
│           └── LC_MESSAGES
│               └── messages.po
```

Supposing that 'String to be translated.' is already translated in .mo file, this should work.

Not working on Homestead. I tried on Local Environment with Apache and works fine.

I hope somebody can figure this out since lot of laravel people are using Homestead.

Any help will be much appreciated.

**Comment by morfin** [comment]
I guess I'll wait till 3.1.2 is released. native php gettext really sucks, it is out-dated and a pain in the ass to deal with.

**Comment by shaggyz** [comment]
Yes that's the plan! If you can wait until 3.1.2. I started working on it today. Thank you.

**Comment by shaggyz** [comment]
Depends on #52

**Comment by shaggyz** [comment]
Closing as duplicate, progress on this behaviour is in #52
