### ISSUE TITLE
Best way to implement into queued e-mails

### ISSUE THREAD

**Issue by canfiax** [xinax/laravel-gettext#72]
I would like gettext to function inside e-mails as well. Currently, the approach I have found is to have users locale stored in the users table, and then inside the e-mail template, say `emails.user.created` I have the following piece of code:

    <?php if(isset($user) && is_object($user)) { \LaravelGettext::getLocale(); \LaravelGettext::setLocale($user->locale()); } // locale ?>

However, it seems nasty and I DontLikeToRepeatMySelf in every email template.

I wonder if someone thought about this, and maybe had implemented a smarter way? I.e. into a service provider or something like that.

**Comment by shaggyz** [comment]
You can write a helper to do this, or a service. It's a laravel/php question, close as off-topic.
