### ISSUE TITLE
gettext:update error if config has changed

### ISSUE THREAD

**Issue by gwenth** [xinax/laravel-gettext#75]
Hi !

I noticed a strange thing when you change your config source-paths the command `gettext:update` will complain about verifying the locale structure, while create won't do anything.
Wouldn't it be a great thing if it could create the file on the run on update ? Here is the diff I suggest :

[fixed-update-config.txt](https://github.com/xinax/laravel-gettext/files/287041/fixed-update-config.txt)

 Have a nice day !

**Comment by shaggyz** [comment]
Thank you. Yes, I think that "create" and "update" actions must be merged into a single one command.
