### ISSUE TITLE
Allow selecting category for locale

### ISSUE THREAD

**Issue by calmos** [xinax/laravel-gettext#77]
Please enhance settings to choose category for locale. Now it sets all categories (LC_ALL), but it would be very useful to have a control of it. Especially with numbers - when locale changes decimal point to something else than dot (".") the echo function (and others that converts number to string) uses it. Example:
`$a = 123.45;`
`echo $a; // can outputs "123,45" or "123.45" or something else`
When it is used in for example generating JS code - it can lead to errors. Now the workaround is to use str_replace() or number_format().

**Comment by bart** [comment]
Would this be possible? I fell into this issue and didn't find a good workaround for it. I'm working on a backend that processes geo data like points, polygons etc. But this only works with dots. So any idea?
