### ISSUE TITLE
setLocale does not store locale

### ISSUE THREAD

**Issue by bart** [xinax/laravel-gettext#78]
Hey guys,

maybe you can help me with this issue, because I'm not sure wether it's a package or system related issue. When I set the locale and output a translated string everything works fine. But if I call the ```LaravelGettext::setLocale($locale)``` method and redirect back it falls back to the default language (in my case English). Maybe it is a session problem or something like this. Do you have an idea?

I'm on a MacBook Pro serving the page by Laravel valet.

Thanks a lot!

**Comment by bart** [comment]
Okay, I found the mistake. You have to put the middleware into the $middlewareGroups array. I think it would be great if you could update the docs accordingly.

**Comment by KasperFranz** [comment]
Might be the same as the issue on #61

**Comment by bart** [comment]
Nope, it's not. It didn't had to do anything with the locales on my OS in my case. You only have to put the middleware into the $middlewareGroups array instead of the $middleware array. That's it.

**Comment by shaggyz** [comment]
Updated docs. Thanks!
