### ISSUE TITLE
Source-path exceptions

### ISSUE THREAD

**Issue by Sundfjord** [xinax/laravel-gettext#86]
Hi,

In my project, I would like to translate the vast majority of the files, but not all.

For example, the storage/framework/views folder is full of cached views that may contain obsolete translations, and I would like to exclude translations in these files from the generated .PO file. I also have a subfolder in resources/views whose translations should not be  included.

Currently, I am specifying every subfolder in resources/views except the one I don't want to include.
Is there a way to specify exceptions from what should be included instead? If not, that would be a very helpful feature to an already great package!

**Comment by shaggyz** [comment]
Hello, currently is not possible to exclude paths, but the storage folder is not completely included by default (just the needed temporal directories with compiled views) you can run ```artisan gettext:update``` in order to clean out deprecated translations. Feel free to send a PR for this enhacenment.
