### ISSUE TITLE
[4.0] Support for Laravel 5.3

### ISSUE THREAD

**Issue by brunogaspar** [xinax/laravel-gettext#87]
Can we update the dependencies on 4.0 to allow this to be installed on Laravel 5.3 please?

Thanks!

**Comment by omacesc** [comment]
when can use this gettext for laravel 5.3?

**Comment by kirov117** [comment]
Laravel 5.3 support would be nice indeed. :smiley:

**Comment by kkomelin** [comment]
I found the built-in Laravel translation system not very convenient compared to i18n approach. This package seems to be a great alternative. I would love to see the translation-related part of this package (__() and _n()) in the Laravel core. But if it's not so easy to achieve, then I would appreciate if this package supported Laravel 5.3.

**Comment by brunogaspar** [comment]
Closing since 4.0 works with Laravel 5.3 :)

**Comment by kkomelin** [comment]
Thanks for the update @brunogaspar !
