### ISSUE TITLE
Refresh the page the translation is back to english again

### ISSUE THREAD

**Issue by infolinematrix** [xinax/laravel-gettext#90]
When I change language the first time it works perfectly. However, when I refresh the page the translation is back to english again, even though the language selector still says "Danish" and getLang returns da_DK.... Then when I run php artisan cache:clear it works the first time I refresh, but second time it is back to english again.

**Comment by trisztan** [comment]
Same problem here. I can't change language. Can you fix it?

**Comment by shaggyz** [comment]
Hi, sorry for the delay. It seems like a cache problem, most commonly known like the *gettext-random-cache bug*. In some systems, the internal gettext cache of the php module gets stuck until you restart the webserver (it's on the docs).

It was discussed here: #52, #45 and here: https://stackoverflow.com/questions/13625659 ,among others.

The solution was to implement the Synfony's translator, released today in [4.x](https://github.com/xinax/laravel-gettext/releases/tag/4.0.1) With the last version this shouldn't happen, feedback about this would be great.
