### ISSUE TITLE
Class 'App' not found in helpers.php:14

### ISSUE THREAD

**Issue by bart** [xinax/laravel-gettext#98]
When I'm trying to install the newest version (4.0.2) on Laravel (5.3.19) I'm getting the following error from composer post install cmd: `Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App' not found in [...]/vendor/xinax/laravel-gettext/src/Xinax/LaravelGettext/Support/helpers.php:14` The error is caused by a string that I try to translate inside of a config file. When I comment every underscore-underscore method in this config file (/config) it works great.

Any idea?

**Comment by shaggyz** [comment]
Mmm, it's strange because App is in root namespace, try adding ```use App;``` to ``` [...]/vendor/xinax/laravel-gettext/src/Xinax/LaravelGettext/Support/helpers.php``` and uncomment ```__```

**Comment by bart** [comment]
What do you mean by "uncomment __" ?

**Comment by shaggyz** [comment]
> What do you mean by "uncomment __" ?

I mean remove all comments you've added

> It's not possible to use a use statement here, because the helpers.php file isn't a class. Using \App::make instead results in the same error message. Hm. Any ideas?

Ok, then can be a problem with your application namespace in your project, as I said App is in root namespace and must be visible globally. Try to create a new fresh empty laravel project, install laravel-gettext and check if the error persist, it should work.

**Comment by spout** [comment]
Experiencing same issue with __() in a config file.

**Comment by shaggyz** [comment]
@spout That's expected. Laravel packages won't work until the framework is loaded, config files are read before anything.

**Comment by spout** [comment]
@shaggyz Thanks ! Will move this somewhere else. @bart issue is caused also by __() in config file.

**Comment by bart** [comment]
AH okay, good to know. But it's working with laravel-gettext 3.1.1. Strange!
