### ISSUE TITLE
po - mo files confusion

### ISSUE THREAD

**Issue by danijelk** [xinax/laravel-gettext#99]
Hi,

we're struggling with cleaning out our old legacy translation methods and replacing it all with laravel-gettext.

Using laravel 5.3 and the new laravel-gettext 4.x we managed to get the translations to work.

But my question is, what is the purpose of .mo files? We used to only use .mo files with our old framework without any .po files inside the LC_MESSAGES & using php-gettext. L-gettext seems to just load the .po file and create a catalogue of the language to simply do a strtr replacement on existing strings. 

The reason I'm asking is cause we're seeing comments in the readme regarding .mo files, and would prefer to only have .mo files in our repo as we always did. But as I see it the symphony handler can only load po files, so one would have to switch it to gettext?

Even when doing a change to gettext handler I got an error in Gettext.php line 92:
        // Sets defaults for boot
        $locale = $this->session->get($this->configuration->getLocale());

$session was not set, so my guess is that it should be something like $this->sessionGet('locale', $this->configuration->getLocale()) instead.

But even with that fix I couldn't get a translation until I added the following to our own middleware:

LaravelGettext::setDomain('vem');

I noticed that if I rename the vem.mo to messages.mo, then it works without the setDomain, It's like it's not accounting for the config file 
    /**
     \* Default domain used for translations: It is the file name for .po and .mo files
     */
    'domain' => 'vem',

So some fun bugs to kill, or is it just me that is having this issue?

**Comment by shaggyz** [comment]
> But my question is, what is the purpose of .mo files? We used to only use .mo files with our old framework without any .po files inside the LC_MESSAGES & using php-gettext. L-gettext seems to just load the .po file and create a catalogue of the language to simply do a strtr replacement on existing strings.

Hi, MO files are the "compiled" version of PO files. As you said, you need both files in order to work with this package. You could change the handler to "gettext", but stay prepared to see strange things. 

I recommend to use the Symfony handler and keep both files on project.

> Even when doing a change to gettext handler I got an error in Gettext.php line 92:
> // Sets defaults for boot
> $locale = $this->session->get($this->configuration->getLocale());


That's weird, check if Session middleware is loaded *before* the laravel-gettext one. It must.
